/**
 * Core types for PR Review Assistant
 */

export type CommentStatus = "pending" | "approved" | "rejected";

export type Severity = "critical" | "high" | "medium" | "low";

/**
 * Side of the diff the comment applies to:
 * - RIGHT: Added lines (green, +) or unchanged context lines
 * - LEFT: Deleted lines (red, -)
 */
export type DiffSide = "LEFT" | "RIGHT";

export type AIProvider =
  | "cursor-cli"
  | "anthropic"
  | "openai"
  | "gemini"
  | "groq"
  | "vscode-lm"
  | "none";

/**
 * A single review comment/finding from AI or host (GitHub/GitLab/Bitbucket).
 *
 * Terminology:
 * - `source`: where the comment came from ('ai' = AI review, 'host' = fetched from remote host)
 * - `hostResolved`/`hostOutdated`: remote state on the host — independent of local `status`
 * - `status`: local user decision (pending/approved/rejected) — does NOT affect host state
 * - `parentId`: set on replies to indicate their parent root comment
 */
export interface ReviewComment {
  id: string;
  file: string;
  line: number;
  endLine?: number;
  /**
   * Which side of the diff this comment applies to:
   * - RIGHT (default): For added lines (+) or context lines
   * - LEFT: For deleted lines (-)
   */
  side: DiffSide;
  severity: Severity;
  issue: string;
  suggestion?: string;
  codeSnippet?: string;
  status: CommentStatus;
  editedText?: string;
  /** When set, shown in IDE instead of "AI Review (severity)" (e.g. host comment author). */
  authorName?: string;
  /** Origin of comment: 'ai' = generated by AI review, 'host' = fetched from GitHub/GitLab/Bitbucket. */
  source: "ai" | "host";
  /** True when the comment's position is no longer valid on the host (code changed since comment was posted). */
  hostOutdated?: boolean;
  /** True when the thread was marked resolved on the host. Independent of local `status`. */
  hostResolved?: boolean;
  /** ID of the parent comment for replies. Undefined means this is a root comment. */
  parentId?: string;
}

/** Supported git hosts for PR/MR review */
export type HostType = "github" | "gitlab" | "bitbucket";

/**
 * Information about a PR (or MR on GitLab, PR on Bitbucket)
 */
export interface PRInfo {
  number: number;
  owner: string;
  repo: string;
  title: string;
  headBranch: string;
  baseBranch: string;
  url: string;
  host: HostType;
}

/**
 * A file changed in the PR
 */
export interface ChangedFile {
  path: string;
  status: "added" | "modified" | "deleted" | "renamed";
  additions: number;
  deletions: number;
  comments: ReviewComment[];
}

/**
 * The complete review state
 */
export interface ReviewState {
  pr: PRInfo | null;
  /** True when reviewing local branch diff (no GitHub PR) */
  isLocalMode: boolean;
  files: ChangedFile[];
  diff: string;
  summary: string | null;
  isLoading: boolean;
  error: string | null;
}

/**
 * Expected JSON output from AI
 */
export interface AIReviewOutput {
  summary: string;
  findings: Array<{
    file: string;
    line: number;
    endLine?: number;
    side?: "LEFT" | "RIGHT";
    severity: string;
    issue: string;
    suggestion?: string;
    codeSnippet?: string;
  }>;
}
